services:
  hicea-web:
    build:
      context: ./application
      platforms:
        - linux/arm64
    image: hiddenberg/hicea-web:latest
    restart: always
    networks:
      - proxynetwork

networks:
  proxynetwork:
    external: true